### ISSUE TITLE
replace `make_module_req_guess` with `module_load_environment` in all EasyBlocks

### ISSUE THREAD

**Issue by lexming** [easybuilders/easybuild-easyblocks#3527]
Tracking issue for the update of all easyblocks relying on `make_module_req_guess` to work with the changes in framework: https://github.com/easybuilders/easybuild-framework/pull/4653 and https://github.com/easybuilders/easybuild-framework/pull/4655

* [x] `a/abaqus.py`: #3578
* [x] `a/advisor.py`: #3551
* [x] `a/anaconda.py`:
  * [x] #3577
  * [x] #3585
* [x] `a/ansys.py`: #3579
* [x] `a/aocc.py`: #3594
* [x] `c/clang.py`: #3586
* [x] `c/cudacompat.py`: #3598 
* [x] `c/cuda.py`: #3587
* [x] `e/eigen.py`: #3599 
* [x] `f/flexiblas.py`:
  * [x] #3529 
  * [x] #3584
* [x] `f/fluent.py`: #3600
* [x] `f/freesurfer.py`: #3601
* [x] `f/freetype.py`: #3604
* [x] `f/fsl.py`: #3606 
* [x] `generic/bundle.py`: #3513
* [x] `generic/conda.py`:
  * [x] #3562 
  * [x] #3585
* [x] `generic/intelbase.py`:
  * [x] #3551
  * [x] #3584
* [x] `generic/perlmodule.py`: #3529
* [x] `generic/pythonpackage.py`: #3530
* [x] `generic/rpm.py`: #3561
* [x] `generic/systemcompiler.py`: #3559 
* [x] `generic/systemmpi.py`: #3560 
* [x] `g/gcc.py`:
  * [x] #3556
  * [x] #3584
* [x] `g/gromacs.py`: #3607 
* [x] `h/hdf5.py`: #3608 
* [x] `i/iccifort.py`:
  * [x] #3550
  * [x] #3584
* [x] `i/icc.py`:
  * [x] #3550
  * [x] #3584
* [x] `i/ifort.py`:
  * [x] #3550
  * [x] #3584
* [x] `i/imkl_fftw.py`: #3612
* [x] `i/imkl.py`:
  * [x] #3555
  * [x] #3584
* [x] `i/impi.py`:
  * [x] #3553
  * [x] #3584
* [x] `i/inspector.py`: #3551
* [x] `i/intel_compilers.py`:
  * [x] #3552
  * [x] #3584
* [x] `i/itac.py`: #3609 
* [x] `j/java.py`: #3610 
* [x] `l/libint.py`: #3611 
* [x] `m/mathematica.py`: #3613 
* [x] `m/molpro.py`: #3615 
* [x] `m/mrtrix.py`: #3616 
* [x] `m/mtl4.py`: #3617 
* [x] `n/neuron.py`: #3618 
* [x] `n/nvhpc.py`: #3628 
* [x] `o/ocaml.py`: #3619 
* [x] `o/optislang.py`: #3620 
* [x] `p/petsc.py`: #3627 
* [x] `p/primer3.py`: #3621
* [x] `p/pytorch.py`: #3622 
* [x] `r/repeatmasker.py`: #3630 
* [x] `r/repeatmodeler.py`: #3630 
* [x] `r/root.py`: #3631 
* [x] `r/r.py`: #3626
* [x] `s/slepc.py`: #3629 
* [x] `t/tinker.py`: #3625
* [x] `t/trinity.py`: #3603
* [x] `v/vep.py`: #3602
* [x] `v/vtune.py`: #3551
* [x] `w/wps.py`: #3596
* [x] `w/wrf.py`: #3596
* [x] `x/xalt.py`: #3593
* [x] `x/xmipp.py`: #3592

**Comment by boegel** [comment]
All done, only the `Bundle` easyblock still has a trace of `make_module_req_guess` now, which is required to support easyblocks outside of our control that still use the deprecated `make_module_req_guess` method and are being used for installing bundle components.
